# Generated by Django 5.1.2 on 2024-12-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='images/default_user.png', upload_to='profile-images/'),
        ),
    ]
