# Generated by Django 5.1.2 on 2025-01-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='average_quiz_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='quizzes_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
