# Generated by Django 5.1.2 on 2025-08-13 17:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_achievements_user_average_quiz_percentage_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailconfirmation',
            unique_together={('user', 'code')},
        ),
        migrations.RemoveField(
            model_name='user',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='user',
            name='average_quiz_percentage',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='quizzes_completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_time',
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='expiration_time',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='emailconfirmation',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='emailconfirmation',
            name='updated_time',
        ),
    ]
