# Generated by Django 5.1.2 on 2024-12-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(default='images/quiz_default.png', upload_to='quiz_images/'),
        ),
    ]
