# Generated by Django 5.1.2 on 2025-08-13 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quizresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddConstraint(
            model_name='quizresult',
            constraint=models.UniqueConstraint(fields=('user', 'quiz'), name='unique_user_quiz_result'),
        ),
    ]
